<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003112950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return "Historique d'écoute : tables track et play";
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE play (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, played_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ms_played INT NOT NULL, skipped BOOLEAN NOT NULL, reason_start VARCHAR(32) NOT NULL, reason_end VARCHAR(32) NOT NULL, user_id INT NOT NULL, track_id VARCHAR(22) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E89DEBAA76ED39539FA67F05ED23C43 ON play (user_id, played_at, track_id)');
        $this->addSql('CREATE INDEX IDX_5E89DEBAA76ED395 ON play (user_id)');
        $this->addSql('CREATE INDEX IDX_5E89DEBA5ED23C43 ON play (track_id)');
        $this->addSql('CREATE TABLE track (id VARCHAR(22) NOT NULL, name TEXT NOT NULL, artist_name TEXT NOT NULL, album_name TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE play ADD CONSTRAINT FK_5E89DEBAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE play ADD CONSTRAINT FK_5E89DEBA5ED23C43 FOREIGN KEY (track_id) REFERENCES track (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE play DROP CONSTRAINT FK_5E89DEBAA76ED395');
        $this->addSql('ALTER TABLE play DROP CONSTRAINT FK_5E89DEBA5ED23C43');
        $this->addSql('DROP TABLE play');
        $this->addSql('DROP TABLE track');
    }
}
