<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003144316 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Journal des retraits (removal) et corbeille (user.trash_playlist_id)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE removal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, restored_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, playlist_id VARCHAR(64) NOT NULL, playlist_name VARCHAR(255) NOT NULL, position INT NOT NULL, added_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, removed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, track_id VARCHAR(22) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4DBB74BA76ED395455180A5 ON removal (user_id, removed_at)');
        $this->addSql('CREATE INDEX IDX_D4DBB74BA76ED395 ON removal (user_id)');
        $this->addSql('CREATE INDEX IDX_D4DBB74B5ED23C43 ON removal (track_id)');
        $this->addSql('ALTER TABLE removal ADD CONSTRAINT FK_D4DBB74BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE removal ADD CONSTRAINT FK_D4DBB74B5ED23C43 FOREIGN KEY (track_id) REFERENCES track (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD trash_playlist_id VARCHAR(64) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE removal DROP CONSTRAINT FK_D4DBB74BA76ED395');
        $this->addSql('ALTER TABLE removal DROP CONSTRAINT FK_D4DBB74B5ED23C43');
        $this->addSql('DROP TABLE removal');
        $this->addSql('ALTER TABLE "user" DROP trash_playlist_id');
    }
}
