<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003122027 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Playlists : tables playlist et playlist_track, durée des titres';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE playlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, owner_name VARCHAR(255) NOT NULL, image_url VARCHAR(1024) DEFAULT NULL, readable BOOLEAN NOT NULL, snapshot_id VARCHAR(255) DEFAULT NULL, spotify_id VARCHAR(64) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D782112DA76ED395A905FC5C ON playlist (user_id, spotify_id)');
        $this->addSql('CREATE INDEX IDX_D782112DA76ED395 ON playlist (user_id)');
        $this->addSql('CREATE TABLE playlist_track (position INT NOT NULL, added_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, playlist_id INT NOT NULL, track_id VARCHAR(22) NOT NULL, PRIMARY KEY (playlist_id, position))');
        $this->addSql('CREATE INDEX IDX_75FFE1E56BBD148 ON playlist_track (playlist_id)');
        $this->addSql('CREATE INDEX IDX_75FFE1E55ED23C43 ON playlist_track (track_id)');
        $this->addSql('ALTER TABLE playlist ADD CONSTRAINT FK_D782112DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE playlist_track ADD CONSTRAINT FK_75FFE1E56BBD148 FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE playlist_track ADD CONSTRAINT FK_75FFE1E55ED23C43 FOREIGN KEY (track_id) REFERENCES track (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track ADD duration_ms INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD playlists_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE playlist DROP CONSTRAINT FK_D782112DA76ED395');
        $this->addSql('ALTER TABLE playlist_track DROP CONSTRAINT FK_75FFE1E56BBD148');
        $this->addSql('ALTER TABLE playlist_track DROP CONSTRAINT FK_75FFE1E55ED23C43');
        $this->addSql('DROP TABLE playlist');
        $this->addSql('DROP TABLE playlist_track');
        $this->addSql('ALTER TABLE track DROP duration_ms');
        $this->addSql('ALTER TABLE "user" DROP playlists_synced_at');
    }
}
